# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: بلاگ کوتاه کننده لینک G02
email: your-email@example.com
description: در این بلاگ اخبار و آموزش‌های مرتبط با سرویس کوتاه کننده لینک G02.ir منتشر میشود.
descriptionmeta: بلاگ سرویس کوتاه کننده لینک گو تو
avatar: https://secure.gravatar.com/avatar/7dc47934ba942297a531525287e596c5?s=140&d=mm&r=g
baseurl: "" # the subpath of your site, e.g. /blog
url: http://blog.g02.ir
email: farhadhpir+g02@gmail.com
permalink: /:title/
github_username: farhadhp
# instagram_username: farhad.hassan.pour
linkedin_username: farhadhp
twitter_username: farhadxfarhad

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus_shortname: http-farhadhp-ir

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
